server:
  port: 8081
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        clusterName: au
        namespace: b5c831ac-b585-48c0-a370-6125839d85f8
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false&characterEncoding=utf-8
    username: root
    password: oaoj3210
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.jay.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.jay: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:10086/eureka